In [167]:
from google.cloud import bigquery
import pandas as pd
# import google.datalab.bigquery as bq

# def get_data_big(name):
#     table = 'bingo-ml-1.market_data.{}'.format(name)
#     fields = ['Date', 'Close']
#     data = bq.Query.from_table(bq.Table(table), fields=fields).execute().result().to_dataframe().set_index('Date')
#     return data['Close']


def get_data(name):
    client = bigquery.Client()
    query = "SELECT Date, Close FROM `bingo-ml-1.market_data.{}` ORDER BY Date".format(name)
    query_job = client.query(query)
    query_job.result() # Wait for result

    table = client.get_table(query_job.destination)
    rows = list(client.list_rows(table))
    return pd.Series([x[1] for x in rows], index=[x[0].date() for x in rows])


closing_data = pd.DataFrame()

# indexes = ['snp', 'nyse', 'djia', 'nikkei', 'hangseng', 'ftse', 'dax', 'aord']
indexes = ['snp', 'nyse', 'djia', 'nikkei', 'hangseng', 'ftse', 'dax', 'aord']

for index in indexes:
    closing_data['{}_close'.format(index)] = get_data(index)

closing_data = closing_data.fillna(method='ffill')

closing_data.describe()

,snp_close,nyse_close,djia_close,nikkei_close,hangseng_close,ftse_close,dax_close,aord_close
count,1447.000000,1447.000000,1447.000000,1447.000000,1447.000000,1447.000000,1447.000000,1447.000000
mean,1549.733275,8920.468489,14017.464990,12529.915089,22245.750485,6100.506356,7965.888030,4913.770143
std,338.278280,1420.830375,2522.948044,3646.022665,2026.412936,553.389736,1759.572713,485.052575
min,1022.580017,6434.810059,9686.480469,8160.009766,16250.269531,4805.799805,5072.330078,3927.600098
25%,1271.239990,7668.234863,11987.635254,9465.930176,20841.259765,5677.899902,6457.090088,4500.250000
50%,1433.189941,8445.769531,13323.360352,10774.150391,22437.439453,6008.899902,7435.209961,4901.100098
75%,1875.510010,10370.324707,16413.575196,15163.069824,23425.334961,6622.650147,9409.709961,5346.150147
max,2130.820068,11239.660156,18312.390625,20868.029297,28442.750000,7104.000000,12374.730469,5954.799805

In [13]:
%connect_info

{
  "stdin_port": 64581,
  "ip": "127.0.0.1",
  "control_port": 64582,
  "hb_port": 64583,
  "signature_scheme": "hmac-sha256",
  "key": "45a5efbe-9ab82f71a1e9da1fa33074a1",
  "kernel_name": "",
  "shell_port": 64579,
  "transport": "tcp",
  "iopub_port": 64580
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-98169645-4937-4c2d-a6df-8e93bbfc6ea5.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.